meta_name: "Chillpill"
meta_title: "Chillpill | A better healthcare for your pet"
meta_description: "Chillpill is a web app that will help you provide the best healthcare to your pet. Manage the schedule for your best friends medications and never miss any!"
meta_image: "chillpill_yellow.png"
